[CmdletBinding()]
param(
    [ValidateSet("Patch", "Minor", "Major")]
    [string]$Bump,

    [string]$SetVersion,

    [string]$Configuration = "Release"
)

$ErrorActionPreference = "Stop"

$projectDir = $PSScriptRoot
$csprojFile = Get-ChildItem -Path $projectDir -Filter "*.csproj" | Select-Object -First 1
if (-not $csprojFile) {
    Write-Error "Could not find a .csproj file in '$projectDir'."
    exit 1
}
$csprojPath = $csprojFile.FullName
[xml]$csproj = Get-Content $csprojPath

$versionNode = $csproj.Project.PropertyGroup | Where-Object { $_.Version } | Select-Object -First 1
$currentVersion = $versionNode.Version
if (-not $currentVersion) { $currentVersion = "1.0.0" }

$newVersion = $null

# 1. Handle Version Bumping if requested
if ($SetVersion) {
    $newVersion = $SetVersion
} elseif ($Bump) {
    $parts = $currentVersion.Split('.')
    [int]$major = if ($parts.Length -gt 0) { [int]$parts[0] } else { 1 }
    [int]$minor = if ($parts.Length -gt 1) { [int]$parts[1] } else { 0 }
    [int]$patch = if ($parts.Length -gt 2) { [int]$parts[2] } else { 0 }

    switch ($Bump) {
        "Major" { $major++; $minor = 0; $patch = 0 }
        "Minor" { $minor++; $patch = 0 }
        "Patch" { $patch++ }
    }

    $newVersion = "$major.$minor.$patch"
}

if ($newVersion -and $newVersion -ne $currentVersion) {
    Write-Host "Updating version: $currentVersion -> $newVersion in $($csprojFile.Name)" -ForegroundColor Cyan
    $versionNode.Version = $newVersion
    $csproj.Save($csprojPath)
    $currentVersion = $newVersion
}

# 2. Extract AssemblyName and Package Metadata
$assemblyName = ($csproj.Project.PropertyGroup | Where-Object { $_.AssemblyName } | Select-Object -First 1).AssemblyName
if (-not $assemblyName) { $assemblyName = [System.IO.Path]::GetFileNameWithoutExtension($csprojPath) }

$packageDescNode = $csproj.Project.PropertyGroup | Where-Object { $_.PackageDescription } | Select-Object -First 1
$packageDesc = if ($packageDescNode) { $packageDescNode.PackageDescription } else { "Valheim BepInEx mod by dreamwraith." }

$packageUrlNode = $csproj.Project.PropertyGroup | Where-Object { $_.PackageWebsiteUrl } | Select-Object -First 1
$packageUrl = if ($packageUrlNode) { $packageUrlNode.PackageWebsiteUrl } else { "https://github.com/dreamwraith/$assemblyName" }

# 3. Synchronize manifest.json
$manifestPath = Join-Path $projectDir "manifest.json"
$dependencies = @("denikson-BepInExPack_Valheim-5.4.2350")
if (Test-Path $manifestPath) {
    try {
        $existingManifest = Get-Content $manifestPath -Raw | ConvertFrom-Json
        if ($existingManifest.dependencies) {
            $dependencies = @($existingManifest.dependencies)
        }
    } catch { }
}

$manifestData = [ordered]@{
    "name" = $assemblyName
    "version_number" = $currentVersion
    "website_url" = $packageUrl
    "description" = $packageDesc
    "dependencies" = $dependencies
}
$manifestJson = $manifestData | ConvertTo-Json -Depth 4
[System.IO.File]::WriteAllText($manifestPath, $manifestJson + [Environment]::NewLine)

# 4. Synchronize obj\VersionInfo.g.cs
$objDir = Join-Path $projectDir "obj"
if (-not (Test-Path $objDir)) { New-Item -ItemType Directory -Path $objDir | Out-Null }
$versionInfoPath = Join-Path $objDir "VersionInfo.g.cs"
$versionInfoContent = @"
// <auto-generated />
namespace $assemblyName
{
    internal static class VersionInfo
    {
        public const string Version = "$currentVersion";
    }
}
"@
[System.IO.File]::WriteAllText($versionInfoPath, $versionInfoContent + [Environment]::NewLine)

# 5. Check DLL Location
$dllSource = Join-Path $projectDir "bin\$Configuration\net48\$assemblyName.dll"
if (-not (Test-Path $dllSource)) {
    $dllSource = Join-Path $projectDir "bin\$Configuration\$assemblyName.dll"
}

if (-not (Test-Path $dllSource)) {
    Write-Error "Could not find compiled assembly at '$dllSource'. Please build the project in $Configuration mode first."
    exit 1
}

# 6. Assemble Zip Package
$outputDir = Join-Path $projectDir "bin\Publish"
$stagingDir = Join-Path $projectDir "bin\PackageTemp"
$zipFile = Join-Path $outputDir "$assemblyName-$currentVersion.zip"

if (Test-Path $stagingDir) { Remove-Item -Recurse -Force $stagingDir }
if (Test-Path $zipFile) { Remove-Item -Force $zipFile }
New-Item -ItemType Directory -Force -Path $stagingDir | Out-Null
New-Item -ItemType Directory -Force -Path $outputDir | Out-Null

Copy-Item $dllSource -Destination $stagingDir
Copy-Item $manifestPath -Destination $stagingDir
if (Test-Path (Join-Path $projectDir "icon.png")) {
    Copy-Item (Join-Path $projectDir "icon.png") -Destination $stagingDir
}
if (Test-Path (Join-Path $projectDir "README.md")) {
    Copy-Item (Join-Path $projectDir "README.md") -Destination $stagingDir
}

$changelog = Join-Path $projectDir "CHANGELOG.md"
if (Test-Path $changelog) {
    Copy-Item $changelog -Destination $stagingDir
}

Compress-Archive -Path "$stagingDir\*" -DestinationPath $zipFile -Force
Remove-Item -Recurse -Force $stagingDir

Write-Host "`nMod package successfully created for v$currentVersion!" -ForegroundColor Green
Write-Host "Location: $zipFile" -ForegroundColor Cyan
return $zipFile
